name: 🧠 Update GitHub Streak Stats

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight UTC
  workflow_dispatch:       # Allow manual runs from Actions tab

jobs:
  update-streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest GitHub Streak image
        run: |
          mkdir -p assets
          curl -L "https://streak-stats.demolab.com?user=Pro-Sifat-Hasan&theme=dark" -o assets/streak-stats.svg

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/streak-stats.svg
          git commit -m "🧠 Update GitHub Streak Stats [skip ci]" || echo "No changes to commit"
          git push
